// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVNu6NgvGHWdHGz_dyeMh-sDa_aDuhpiw',
    appId: '1:896389693617:web:a13f47326de5b84ca8a290',
    messagingSenderId: '896389693617',
    projectId: 'ayaaa-56823',
    authDomain: 'ayaaa-56823.firebaseapp.com',
    storageBucket: 'ayaaa-56823.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxentfpTDDPA-MG_Ml7R3J7AbYJ5Vrztw',
    appId: '1:896389693617:android:c164b90e21163012a8a290',
    messagingSenderId: '896389693617',
    projectId: 'ayaaa-56823',
    storageBucket: 'ayaaa-56823.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoXa7Mf1SdiE1VWD4cN5pM_pqtJSfzNNM',
    appId: '1:896389693617:ios:dde7eab0a92bad72a8a290',
    messagingSenderId: '896389693617',
    projectId: 'ayaaa-56823',
    storageBucket: 'ayaaa-56823.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoXa7Mf1SdiE1VWD4cN5pM_pqtJSfzNNM',
    appId: '1:896389693617:ios:dde7eab0a92bad72a8a290',
    messagingSenderId: '896389693617',
    projectId: 'ayaaa-56823',
    storageBucket: 'ayaaa-56823.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVNu6NgvGHWdHGz_dyeMh-sDa_aDuhpiw',
    appId: '1:896389693617:web:135c89c400fa48eca8a290',
    messagingSenderId: '896389693617',
    projectId: 'ayaaa-56823',
    authDomain: 'ayaaa-56823.firebaseapp.com',
    storageBucket: 'ayaaa-56823.firebasestorage.app',
  );
}
